---
name: "Pull Request: Validate"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  pr-metadata:
    uses: cdloh/containers/.github/workflows/pr-metadata.yaml@main

  generate-build-matrix:
    name: Generate matrix for building images
    runs-on: ubuntu-22.04
    needs:
      - pr-metadata
    outputs:
      matrix: ${{ steps.get-changed.outputs.changes }}
    if: ${{ needs.pr-metadata.outputs.addedOrModifiedImages }} != '[]'
    steps:
      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch modified images
        id: get-changed
        shell: bash
        run: ./.github/scripts/fetch-modified-images.sh

  images-build:
    uses: cdloh/containers/.github/workflows/action-image-build.yaml@main
    needs:
      - generate-build-matrix
    with:
      imagesToBuild: "${{ needs.generate-build-matrix.outputs.matrix }}"
      updateMetadata: "false"
      sendNotification: "false"
    secrets: inherit
